#!/bin/sh

set -e

if [ ! -e /usr/bin/gnome-screensaver ]; then
  echo "Linking /usr/bin/gnome-screensaver to /usr/bin/cinnamon-screensaver"
  ln -s /usr/bin/cinnamon-screensaver /usr/bin/gnome-screensaver
fi

if [ ! -e /usr/bin/gnome-screensaver-command ]; then
  echo "Linking /usr/bin/gnome-screensaver-command to /usr/bin/cinnamon-screensaver-command"
  ln -s /usr/bin/cinnamon-screensaver-command /usr/bin/gnome-screensaver-command
fi

#DEBHELPER#

exit 0
